---
- name: download ranger git repo
  git:
    repo: "{{ ranger_repo }}"
    dest: "{{ ranger_download_directory }}" 
    version: "{{ ranger_branch }}"

- name: install build packages
  become: true
  package:
    name:
      - make
      - git
      - vim
    state: present

- name: Run 'install' target as root
  become: yes
  make:
    chdir: "{{ ranger_download_directory }}"
    target: install
  when: ansible_python_version[:1] == '3'

- name: install python3
  become: true
  package:
    name: python3
    state: present

- name: install ranger with python3
  become: yes
  command: python3 setup.py install --optimize=1
  args:
    chdir: "{{ ranger_download_directory }}"
    creates: '/usr/local/bin/ranger'
