---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install ranger
  become: yes
  package:
    name: ranger
    state: present
  register: install_ranger
  ignore_errors: yes

- include_tasks: compile_ranger.yml
  when: install_ranger.failed
