---
- name: combine ranger configuration
  ansible.builtin.set_fact:
    ranger: "{{ _ranger|combine(ranger, recursive=True) }}"

- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install ranger
  become: true
  ansible.builtin.package:
    name: ranger
    state: present
  register: install_ranger
  ignore_errors: true

- name: compile ranger if install failed
  ansible.builtin.include_tasks: compile_ranger.yml
  when: install_ranger.failed
